### ISSUE TITLE
About adjusting output size of VGG

### ISSUE THREAD

**Issue by qqcce** [pierrebaque/EM#27]
Hi,
The BG output size is resized 4x4 times smaller than input according to VGG model(self.VGGout_resize = 16), resulting in a loss of detail.
Is there a way to get a BG with size not re-scaled?

**Comment by lc-git** [comment]
same question, how to keep the size of origin image

**Comment by pierrebaque** [comment]
Hello,

In my framework, this is not possible since I did not need such a high quality segmentation. However, if you look at the semantic segmentation litterature, you will find many strategies for upsampling the feature maps inside the CNN and therefore recovering the initial quality of the segmentation. It should be not too difficult to integrate it in the Deep Occlusion code.

Cheers
